# Aider Evaluation - Metrics-Based Assessment
# Real-world verifiable data for research decision-making

tool_name = "aider"
tool_display_name = "Aider"
summary = "Aider is an open-source AI pair programming tool with strong GitHub integration, active development, and community-driven features."

[metrics.github]
repo_url = "https://github.com/paul-gauthier/aider"
stars = 18000
forks = 1600
open_issues = 85
last_commit_date = "2025-10-03"
commit_frequency = "Daily"
contributors = 120
license = "Apache-2.0"
created_date = "2023-05-15"
archived = false

[metrics.package]
package_name = "aider-chat"
registry = "PyPI"
weekly_downloads = 15000
total_downloads = 1200000
latest_version = "0.48.0"
last_publish_date = "2025-10-01"
version_count = 248

[metrics.community]
discord_members = 5000
discord_url = "https://discord.gg/aider"
twitter_followers = 12000
twitter_url = "https://twitter.com/aider_ai"
reddit_subscribers = 3500
reddit_url = "https://reddit.com/r/aider"
active_discussions = true

[metrics.documentation]
docs_url = "https://aider.chat/docs"
has_readme = true
has_contributing_guide = true
has_examples = true
docs_freshness = "< 1 week"
api_docs_quality = "Good"

[metrics.platform]
supported_os = ["macOS", "Linux", "Windows"]
supported_languages = ["Python"]
architectures = ["x86_64", "ARM64"]
requires_docker = false
docker_support = true
ci_cd_setup = true
cloud_deployment_guides = false
web_based = false
mobile_support = false
cloud_only = false

[metrics.team]
doxxed_team = true
organization_name = "Paul Gauthier"
organization_url = "https://aider.chat"
team_size = "Small (1-5)"
public_team = true
company_funding = "Open Source / Self-funded"
backed_by = ["Community"]
funding_disclosed = true
public_roadmap = true
security_audits = false
security_policy = true
responsible_disclosure = true

[metrics.support]
avg_issue_response_time = "< 48 hours"
avg_pr_review_time = "< 72 hours"
avg_issue_close_time = "5-7 days"
open_vs_closed_ratio = 0.18
active_maintainers = 3
has_paid_support = false
commercial_support = false
community_support = "GitHub Issues, Discord"
support_channels = ["GitHub Issues", "Discord"]
sla_available = false
uptime_percentage = 99.5
