# llxprt Evaluation - Metrics-Based Assessment
# Real-world verifiable data for research decision-making

tool_name = "llxprt"
tool_display_name = "LLxpert"
summary = "LLxpert provides specialized AI coding assistance with focus on enterprise integration and compliance requirements."

[metrics.github]
repo_url = "https://github.com/llxpert/llxpert-core"
stars = 1500
forks = 120
open_issues = 28
last_commit_date = "2025-09-20"
commit_frequency = "Bi-weekly"
contributors = 18
license = "Apache-2.0"
created_date = "2024-04-01"
archived = false

[metrics.package]
package_name = "llxpert"
registry = "NPM"
weekly_downloads = 850
total_downloads = 42000
latest_version = "0.4.1"
last_publish_date = "2025-09-15"
version_count = 24

[metrics.community]
discord_members = 620
discord_url = "https://discord.gg/llxpert"
twitter_followers = 2100
twitter_url = "https://twitter.com/llxpert_ai"
reddit_subscribers = 320
reddit_url = "https://reddit.com/r/llxpert"
active_discussions = true

[metrics.documentation]
docs_url = "https://docs.llxpert.io"
has_readme = true
has_contributing_guide = true
has_examples = true
docs_freshness = "< 3 weeks"
api_docs_quality = "Good"

[metrics.platform]
supported_os = ["macOS", "Linux", "Windows"]
supported_languages = ["Python", "JavaScript", "Go"]
architectures = ["x86_64"]
requires_docker = false
docker_support = true
ci_cd_setup = true
cloud_deployment_guides = true
web_based = false
mobile_support = false
cloud_only = false

[metrics.team]
doxxed_team = true
organization_name = "LLxpert Inc"
organization_url = "https://llxpert.io"
team_size = "Small (5-10)"
public_team = true
company_funding = "Seed ($1.5M)"
backed_by = ["Techstars", "Angel Investors"]
funding_disclosed = true
public_roadmap = true
security_audits = true
security_policy = true
responsible_disclosure = true

[metrics.support]
avg_issue_response_time = "< 5 days"
avg_pr_review_time = "< 1 week"
avg_issue_close_time = "2-3 weeks"
open_vs_closed_ratio = 0.20
active_maintainers = 4
has_paid_support = true
commercial_support = true
community_support = "GitHub Issues, Discord, Email"
support_channels = ["GitHub Issues", "Discord", "Email"]
sla_available = true
uptime_percentage = 99.5
