# Amp Evaluation - Metrics-Based Assessment
# Real-world verifiable data for research decision-making

tool_name = "amp"
tool_display_name = "Amp"
summary = "Amp focuses on terminal-based AI coding workflows with minimalist design and efficient resource usage."

[metrics.github]
repo_url = "https://github.com/jmacdonald/amp"
stars = 3800
forks = 190
open_issues = 38
last_commit_date = "2025-08-15"
commit_frequency = "Monthly"
contributors = 22
license = "GPL-3.0"
created_date = "2016-03-20"
archived = false

[metrics.package]
package_name = "amp-editor"
registry = "Crates.io"
weekly_downloads = 450
total_downloads = 65000
latest_version = "0.7.0"
last_publish_date = "2025-07-10"
version_count = 28

[metrics.community]
discord_members = 450
reddit_subscribers = 280
reddit_url = "https://reddit.com/r/amp"
active_discussions = false

[metrics.documentation]
docs_url = "https://amp.rs"
has_readme = true
has_contributing_guide = true
has_examples = true
docs_freshness = "< 1 month"
api_docs_quality = "Adequate"

[metrics.platform]
supported_os = ["macOS", "Linux"]
supported_languages = ["Rust"]
architectures = ["x86_64", "ARM64"]
requires_docker = false
docker_support = false
ci_cd_setup = true
cloud_deployment_guides = false
web_based = false
mobile_support = false
cloud_only = false

[metrics.team]
doxxed_team = true
organization_name = "Jordan Macdonald"
organization_url = "https://github.com/jmacdonald"
team_size = "Small (1-5)"
public_team = true
company_funding = "Open Source / Self-funded"
backed_by = ["Community"]
funding_disclosed = true
public_roadmap = false
security_audits = false
security_policy = true
responsible_disclosure = true

[metrics.support]
avg_issue_response_time = "< 1 week"
avg_pr_review_time = "< 2 weeks"
avg_issue_close_time = "2-4 weeks"
open_vs_closed_ratio = 0.25
active_maintainers = 2
has_paid_support = false
commercial_support = false
community_support = "GitHub Issues"
support_channels = ["GitHub Issues"]
sla_available = false
uptime_percentage = 98.0
