# Gemini Evaluation - Metrics-Based Assessment
# Real-world verifiable data for research decision-making

tool_name = "gemini"
tool_display_name = "Google Gemini"
summary = "Google's Gemini provides enterprise-grade AI with deep integration into Google Cloud ecosystem, strong multilingual support, and competitive pricing."

[metrics.github]
repo_url = "https://github.com/google-gemini/generative-ai-python"
stars = 5200
forks = 850
open_issues = 120
last_commit_date = "2025-09-30"
commit_frequency = "Daily"
contributors = 45
license = "Apache-2.0"
created_date = "2023-12-15"
archived = false

[metrics.package]
package_name = "@google-cloud/vertexai"
registry = "NPM"
weekly_downloads = 12000
total_downloads = 800000
latest_version = "1.2.3"
last_publish_date = "2025-09-25"
version_count = 68

[metrics.community]
discord_members = 8000
discord_url = "https://discord.gg/google-ai"
twitter_followers = 120000
twitter_url = "https://twitter.com/GoogleAI"
reddit_subscribers = 15000
reddit_url = "https://reddit.com/r/GoogleAI"
active_discussions = true

[metrics.documentation]
docs_url = "https://ai.google.dev/docs"
has_readme = true
has_contributing_guide = true
has_examples = true
docs_freshness = "< 1 week"
api_docs_quality = "Excellent"

[metrics.platform]
supported_os = ["macOS", "Linux", "Windows"]
supported_languages = ["Python", "JavaScript", "TypeScript", "Go", "Java"]
architectures = ["x86_64", "ARM64"]
requires_docker = false
docker_support = true
ci_cd_setup = true
cloud_deployment_guides = true
web_based = true
mobile_support = true
cloud_only = false

[metrics.team]
doxxed_team = true
organization_name = "Google LLC"
organization_url = "https://ai.google.dev"
team_size = "Large (1000+)"
public_team = true
company_funding = "Public Company"
backed_by = ["Alphabet Inc"]
funding_disclosed = true
public_roadmap = true
security_audits = true
security_policy = true
responsible_disclosure = true

[metrics.support]
avg_issue_response_time = "< 48 hours"
avg_pr_review_time = "< 72 hours"
avg_issue_close_time = "5-7 days"
open_vs_closed_ratio = 0.12
active_maintainers = 25
has_paid_support = true
commercial_support = true
community_support = "GitHub Issues, Stack Overflow, Discord"
support_channels = [
    "GitHub Issues",
    "Discord",
    "Stack Overflow",
    "Enterprise Support",
]
sla_available = true
uptime_percentage = 99.95
