# Goose Evaluation - Metrics-Based Assessment
# Real-world verifiable data for research decision-making

tool_name = "goose"
tool_display_name = "Goose AI"
summary = "Goose provides flexible AI coding assistance with multiple provider support, active development, and growing community adoption."

[metrics.github]
repo_url = "https://github.com/block/goose"
stars = 3500
forks = 280
open_issues = 45
last_commit_date = "2025-09-28"
commit_frequency = "Weekly"
contributors = 35
license = "Apache-2.0"
created_date = "2024-01-15"
archived = false

[metrics.package]
package_name = "goose-ai"
registry = "PyPI"
weekly_downloads = 2500
total_downloads = 150000
latest_version = "0.9.2"
last_publish_date = "2025-09-20"
version_count = 45

[metrics.community]
discord_members = 1200
discord_url = "https://discord.gg/goose"
twitter_followers = 5000
twitter_url = "https://twitter.com/goose_ai"
reddit_subscribers = 800
reddit_url = "https://reddit.com/r/gooseai"
active_discussions = true

[metrics.documentation]
docs_url = "https://block.github.io/goose"
has_readme = true
has_contributing_guide = true
has_examples = true
docs_freshness = "< 2 weeks"
api_docs_quality = "Good"

[metrics.platform]
supported_os = ["macOS", "Linux", "Windows"]
supported_languages = ["Python", "TypeScript"]
architectures = ["x86_64", "ARM64"]
requires_docker = false
docker_support = true
ci_cd_setup = true
cloud_deployment_guides = false
web_based = false
mobile_support = false
cloud_only = false

[metrics.team]
doxxed_team = true
organization_name = "Block (Square)"
organization_url = "https://block.xyz"
team_size = "Medium (10-50)"
public_team = true
company_funding = "Public Company (NYSE: SQ)"
backed_by = ["Block Inc"]
funding_disclosed = true
public_roadmap = true
security_audits = true
security_policy = true
responsible_disclosure = true

[metrics.support]
avg_issue_response_time = "< 72 hours"
avg_pr_review_time = "< 5 days"
avg_issue_close_time = "7-10 days"
open_vs_closed_ratio = 0.22
active_maintainers = 8
has_paid_support = false
commercial_support = false
community_support = "GitHub Issues, Discord"
support_channels = ["GitHub Issues", "Discord"]
sla_available = false
uptime_percentage = 99.0
